"""
Controller Transpiler: controller DSL → PL/SQL package

Example input:
    controller Posts
      before_action :require_login, except: [:index, :show]

      def index
        @posts = Post.all.paginate(params[:page])
        render "posts/index"
      end

      def create
        @post = Post.new(permit(:title, :body))
        if @post.save
          redirect_to "/posts/#{@post.id}", flash: "投稿しました！"
        else
          render "posts/new"
        end
      end
    end
"""

import re
from .parser_utils import (
    parse_symbol, parse_symbol_list, parse_hash_opts,
    extract_block, camel_to_snake, pluralize, ParseError
)


class ControllerTranspiler:
    def __init__(self, source: str, filename: str = "<unknown>"):
        self.source = source
        self.filename = filename
        self.lines = source.split("\n")
        self.controller_name = ""
        self.package_name = ""
        self.before_actions = []
        self.actions = []

    def transpile(self) -> str:
        self._parse()
        spec = self._generate_spec()
        body = self._generate_body()
        return f"{spec}\n/\n\n{body}\n/\n"

    # ================================================================
    # Parsing
    # ================================================================

    def _parse(self):
        i = 0
        while i < len(self.lines):
            line = self.lines[i].strip()

            if not line or line.startswith("#"):
                i += 1
                continue

            # controller Name
            m = re.match(r'^controller\s+(\w+)', line)
            if m:
                self.controller_name = m.group(1)
                snake = camel_to_snake(self.controller_name)
                # Ensure it ends with _controller
                if not snake.endswith("_controller"):
                    self.package_name = snake + "_controller"
                else:
                    self.package_name = snake
                i += 1
                continue

            # before_action :method, only/except: [...]
            if line.startswith("before_action "):
                self._parse_before_action(line)
                i += 1
                continue

            # def action_name ... end
            if line.startswith("def "):
                block_lines, end_i = extract_block(self.lines, i, "def", "end")
                self._parse_action(block_lines)
                i = end_i + 1
                continue

            if line == "end":
                i += 1
                continue

            i += 1

    def _parse_before_action(self, line: str):
        rest = line[14:].strip()  # after "before_action "
        parts = rest.split(",", 1)
        method = parse_symbol(parts[0])
        opts = parse_hash_opts(parts[1]) if len(parts) > 1 else {}
        self.before_actions.append({"method": method, **opts})

    def _parse_action(self, lines: list):
        header = lines[0].strip()
        m = re.match(r'^def\s+(\w+)', header)
        if not m:
            return
        name = m.group(1)
        body_lines = lines[1:-1]  # exclude def and end
        self.actions.append({
            "name": name,
            "body_lines": body_lines
        })

    # ================================================================
    # Spec Generation
    # ================================================================

    def _generate_spec(self) -> str:
        lines = []
        lines.append(f"-- Generated by Hinoki Transpiler from {self.filename}")
        lines.append(f"-- Controller: {self.controller_name}")
        lines.append(f"CREATE OR REPLACE PACKAGE {self.package_name} AS")
        lines.append("")

        for action in self.actions:
            lines.append(f"    PROCEDURE {action['name']};")

        # before_action callback procedures (private, but declared in spec if referenced)
        lines.append("")
        lines.append(f"END {self.package_name};")
        return "\n".join(lines)

    # ================================================================
    # Body Generation
    # ================================================================

    def _generate_body(self) -> str:
        lines = []
        lines.append(f"CREATE OR REPLACE PACKAGE BODY {self.package_name} AS")
        lines.append("")

        for action in self.actions:
            lines.extend(self._generate_action(action))
            lines.append("")

        lines.append(f"END {self.package_name};")
        return "\n".join(lines)

    def _generate_action(self, action: dict) -> list:
        lines = []
        name = action["name"]

        # Collect instance variables (@var) used in body to declare them
        body_plsql = self._transpile_action_body(action["body_lines"])
        ivars = self._collect_instance_vars(action["body_lines"])

        lines.append(f"    PROCEDURE {name} IS")

        # Variable declarations
        declared = set()
        for ivar in ivars:
            var_name = f"v_{ivar}"
            if var_name not in declared:
                # Try to infer type from usage
                if ivar.endswith("s") or ivar == "pagination":
                    lines.append(f"        {var_name} CLOB;")
                elif ivar in ("id", "page", "count"):
                    lines.append(f"        {var_name} NUMBER;")
                else:
                    lines.append(f"        {var_name} VARCHAR2(32767);")
                declared.add(var_name)

        # Standard useful vars
        if any("params[:id]" in l or "params[:page]" in l
               for l in (ll.strip() for ll in action["body_lines"])):
            if "v_id" not in declared:
                lines.append("        v_id NUMBER;")
            if "v_page" not in declared:
                lines.append("        v_page NUMBER;")

        if any("permit(" in l.strip() for l in action["body_lines"]):
            lines.append("        v_params hinoki_model.t_record;")

        if any(".save" in l.strip() for l in action["body_lines"]):
            lines.append("        v_new_id NUMBER;")

        if any(re.search(r'\w+\.find\b', l.strip()) for l in action["body_lines"]):
            lines.append("        v_cursor SYS_REFCURSOR;")
            lines.append("        v_cols DBMS_SQL.desc_tab;")
            lines.append("        v_col_cnt NUMBER;")
            lines.append("        v_cid NUMBER;")
            lines.append("        v_val VARCHAR2(32767);")

        lines.append("    BEGIN")

        # Before actions
        for ba in self.before_actions:
            applies = True
            if "only" in ba:
                applies = name in ba["only"]
            if "except" in ba:
                applies = name not in ba["except"]
            if applies:
                lines.append(f"        {ba['method']};")

        # Action body
        for pl in body_plsql:
            lines.append(f"        {pl}")

        lines.append(f"    EXCEPTION WHEN OTHERS THEN")
        lines.append(f"        hinoki_core.log_error('{self.package_name}.{name}: ' || SQLERRM);")
        lines.append(f"        hinoki_core.respond_500(SQLERRM);")
        lines.append(f"    END {name};")
        return lines

    def _transpile_action_body(self, body_lines: list) -> list:
        """Transpile Ruby-like action body to PL/SQL statements."""
        result = []
        i = 0
        raw_lines = [l.rstrip() for l in body_lines]

        while i < len(raw_lines):
            line = raw_lines[i].strip()

            if not line or line.startswith("#"):
                i += 1
                continue

            # ----- render "template" -----
            m = re.match(r'^render\s+"([^"]+)"(?:\s*,\s*(.+))?', line)
            if m:
                template = m.group(1)
                opts = parse_hash_opts(m.group(2)) if m.group(2) else {}
                status = opts.get("status", 200)
                layout = opts.get("layout")
                layout_str = f"'{layout}'" if layout else "NULL"
                result.append(f"hinoki_view.render_to('{template}', {layout_str}, {status});")
                i += 1
                continue

            # ----- render_json @var -----
            m = re.match(r'^render_json\s+@(\w+)', line)
            if m:
                result.append(f"hinoki_core.respond_json(v_{m.group(1)});")
                i += 1
                continue

            # ----- redirect_to "url", flash: "msg" -----
            m = re.match(r'^redirect_to\s+"([^"]*)"(?:\s*,\s*(.+))?', line)
            if m:
                url = self._transpile_string_interpolation(m.group(1))
                opts = parse_hash_opts(m.group(2)) if m.group(2) else {}
                flash_msg = opts.get("flash", "")
                flash_type = opts.get("flash_type", "success")
                if flash_msg:
                    result.append(f"hinoki_controller.redirect_to({url}, "
                                  f"'{flash_msg}', '{flash_type}');")
                else:
                    result.append(f"hinoki_controller.redirect_to({url});")
                i += 1
                continue

            # ----- @var = Model.find(params[:id]) -----
            m = re.match(r'^@(\w+)\s*=\s*(\w+)\.find\(params\[:id\]\)', line)
            if m:
                ivar = m.group(1)
                model = camel_to_snake(m.group(2))
                result.append(f"v_id := hinoki_core.param_int('id');")
                result.append(f"v_cursor := {model}_model.find(v_id);")
                result.append(self._emit_cursor_to_view_vars("v_cursor"))
                i += 1
                continue

            # ----- @var = Model.all / Model.scope.paginate(...) -----
            m = re.match(r'^@(\w+)\s*=\s*(\w+)\.([\w.]+?)(?:\.paginate\(([^)]*)\))?$', line)
            if m:
                ivar = m.group(1)
                model = camel_to_snake(m.group(2))
                chain = m.group(3)
                paginate_arg = m.group(4)

                if paginate_arg:
                    page_expr = self._transpile_expr(paginate_arg.strip())
                    if chain == "all":
                        result.append(f"v_page := NVL({page_expr}, 1);")
                        result.append(f"hinoki_view.assign_collection('{ivar}', "
                                      f"{model}_model.all_records(v_page));")
                    else:
                        result.append(f"v_page := NVL({page_expr}, 1);")
                        result.append(f"hinoki_view.assign_collection('{ivar}', "
                                      f"{model}_model.{chain}(v_page));")
                else:
                    if chain == "all":
                        result.append(f"hinoki_view.assign_collection('{ivar}', "
                                      f"hinoki_model.find_all({model}_model.c_table));")
                    else:
                        result.append(f"hinoki_view.assign_collection('{ivar}', "
                                      f"{model}_model.{chain});")
                i += 1
                continue

            # ----- @var = Model.new(permit(:cols)) -----
            m = re.match(r'^@(\w+)\s*=\s*(\w+)\.new\(permit\(([^)]+)\)\)', line)
            if m:
                ivar = m.group(1)
                model = camel_to_snake(m.group(2))
                cols = ", ".join(parse_symbol_list(m.group(3)))
                result.append(f"v_params := hinoki_controller.permit('{cols}');")
                i += 1
                continue

            # ----- @pagination = Model.pagination_info(...) -----
            m = re.match(r'^@pagination\s*=\s*(\w+)\.pagination_info\(([^)]*)\)', line)
            if m:
                model = camel_to_snake(m.group(1))
                args = m.group(2).strip()
                page_expr = self._transpile_expr(args) if args else "v_page"
                result.append(f"hinoki_view.assign_raw('pagination', "
                              f"hinoki_model.pagination_html("
                              f"hinoki_model.pagination_info({model}_model.c_table, {page_expr}), "
                              f"'/' || {model}_model.c_table));")
                i += 1
                continue

            # ----- if @obj.save -----
            m = re.match(r'^if\s+@(\w+)\.save', line)
            if m:
                ivar = m.group(1)
                model = camel_to_snake(m.group(1))
                result.append(f"v_new_id := {model}_model.create_record(v_params);")
                result.append("IF v_new_id IS NOT NULL THEN")
                i += 1
                continue

            # ----- if @obj.update(permit(...)) -----
            m = re.match(r'^if\s+@(\w+)\.update\(permit\(([^)]+)\)\)', line)
            if m:
                model = camel_to_snake(m.group(1))
                cols = ", ".join(parse_symbol_list(m.group(2)))
                result.append(f"v_params := hinoki_controller.permit('{cols}');")
                result.append(f"{model}_model.update_record(v_id, v_params);")
                result.append("IF hinoki_model.error_count = 0 THEN")
                i += 1
                continue

            # ----- Model.delete(params[:id]) -----
            m = re.match(r'^(\w+)\.delete\(params\[:id\]\)', line)
            if m:
                model = camel_to_snake(m.group(1))
                result.append(f"v_id := hinoki_core.param_int('id');")
                result.append(f"{model}_model.delete_record(v_id);")
                i += 1
                continue

            # ----- @var.update(permit(...)) without if -----
            m = re.match(r'^@(\w+)\.update\(permit\(([^)]+)\)\)', line)
            if m:
                model = camel_to_snake(m.group(1))
                cols = ", ".join(parse_symbol_list(m.group(2)))
                result.append(f"v_params := hinoki_controller.permit('{cols}');")
                result.append(f"{model}_model.update_record(v_id, v_params);")
                i += 1
                continue

            # ----- @var = "string" (assign to view) -----
            m = re.match(r'^@(\w+)\s*=\s*"([^"]*)"', line)
            if m:
                result.append(f"hinoki_view.assign('{m.group(1)}', '{m.group(2)}');")
                i += 1
                continue

            # ----- @var = expr (generic view assign) -----
            m = re.match(r'^@(\w+)\s*=\s*(.+)', line)
            if m:
                expr = self._transpile_expr(m.group(2).strip())
                result.append(f"hinoki_view.assign('{m.group(1)}', {expr});")
                i += 1
                continue

            # ----- else -----
            if line == "else":
                result.append("ELSE")
                i += 1
                continue

            # ----- elsif cond -----
            m = re.match(r'^elsif\s+(.+)', line)
            if m:
                cond = self._transpile_expr(m.group(1))
                result.append(f"ELSIF {cond} THEN")
                i += 1
                continue

            # ----- end -----
            if line == "end":
                result.append("END IF;")
                i += 1
                continue

            # ----- raw_plsql <<~SQL ... SQL -----
            if line.startswith("raw_plsql"):
                raw_lines = []
                i += 1
                while i < len(raw_lines) and raw_lines[i].strip() != "SQL":
                    raw_lines.append(raw_lines[i])
                    i += 1
                result.extend(raw_lines)
                i += 1
                continue

            # ----- Generic expression -----
            result.append(self._transpile_expr(line) + ";")
            i += 1

        return result

    def _transpile_expr(self, expr: str) -> str:
        """Transpile a Ruby-like expression to PL/SQL."""
        # params[:key] → hinoki_core.param('key') or param_int
        expr = re.sub(r'params\[:(\w+)\]',
                       lambda m: f"hinoki_core.param_int('{m.group(1)}')"
                       if m.group(1) in ("id", "page", "per_page")
                       else f"hinoki_core.param('{m.group(1)}')", expr)

        # @obj.id → v_new_id or v_id
        expr = re.sub(r'@\w+\.id\b', 'v_new_id', expr)

        # String interpolation: "...#{expr}..." → '...' || expr || '...'
        if '"' in expr and '#{' in expr:
            expr = self._transpile_string_interpolation(expr.strip('"'))

        return expr

    def _transpile_string_interpolation(self, s: str) -> str:
        """Convert Ruby string interpolation to PL/SQL concatenation.
        "hello #{name}" → 'hello ' || name
        """
        parts = re.split(r'#\{([^}]+)\}', s)
        sql_parts = []
        for idx, part in enumerate(parts):
            if idx % 2 == 0:
                # String literal part
                if part:
                    sql_parts.append(f"'{part}'")
            else:
                # Expression part
                expr = self._transpile_expr(part)
                sql_parts.append(expr)
        return " || ".join(sql_parts) if sql_parts else "''"

    def _collect_instance_vars(self, body_lines: list) -> list:
        """Collect all @var names from body."""
        ivars = set()
        for line in body_lines:
            for m in re.finditer(r'@(\w+)', line):
                name = m.group(1)
                if name not in ("post", "posts", "comment", "comments"):
                    ivars.add(name)
        return sorted(ivars)

    def _emit_cursor_to_view_vars(self, cursor_var: str) -> str:
        """Emit PL/SQL to read cursor row into view variables."""
        return (
            f"{cursor_var}_cid := DBMS_SQL.to_cursor_number({cursor_var});\n"
            f"        DBMS_SQL.describe_columns({cursor_var}_cid, v_col_cnt, v_cols);\n"
            f"        FOR i IN 1..v_col_cnt LOOP\n"
            f"            DBMS_SQL.define_column({cursor_var}_cid, i, v_val, 32767);\n"
            f"        END LOOP;\n"
            f"        IF DBMS_SQL.fetch_rows({cursor_var}_cid) > 0 THEN\n"
            f"            FOR i IN 1..v_col_cnt LOOP\n"
            f"                DBMS_SQL.column_value({cursor_var}_cid, i, v_val);\n"
            f"                hinoki_view.assign(LOWER(v_cols(i).col_name), v_val);\n"
            f"            END LOOP;\n"
            f"        ELSE\n"
            f"            DBMS_SQL.close_cursor({cursor_var}_cid);\n"
            f"            hinoki_core.respond_404;\n"
            f"            RETURN;\n"
            f"        END IF;\n"
            f"        DBMS_SQL.close_cursor({cursor_var}_cid);"
        ).replace(f"{cursor_var}_cid", "v_cid")
